function defaults = ipceDefaultConfig
%IPCEDEFAULTCONFIG Return durable startup defaults for the IPCE app.

defaults = struct( ...
    "CalibrationFile", ...
    "标准硅探测器校准结果_证书编号 GXgf2026-01645.xlsx", ...
    "SpectrumFile", "标准太阳能光谱数据.xls", ...
    "SiliconTraceFile", ...
    "Si-i t [300 1100] nm-grating 2-filter.txt", ...
    "SiliconAnchorFile", ...
    "Si-i t [300 1100] nm-grating 2-filter-time match.txt", ...
    "SubtractDark", true, ...
    "SiliconDarkRange_s", [0.1, 10], ...
    "SampleDarkRange_s", [50, 60]);
end
