function [lightResult, ipceResult] = ipceCalculate(calibration, ...
    siliconExtracted, sampleExtracted, siliconArea_cm2, sampleArea_cm2)
%IPCECALCULATE Calculate incident power density and, optionally, IPCE.
%   P_density(lambda) = abs(Delta I_Si) / ...
%       (R_Si(lambda) * A_Si)
%   IPCE(%) = 100 * (h*c/q) * ...
%       (abs(Delta I_sample) / A_sample) / (P_density*lambda)
%   With lambda in nm, (h*c/q) becomes 1239.841984 eV*nm.

arguments
    calibration table
    siliconExtracted table
    sampleExtracted = table()
    siliconArea_cm2 (1, 1) double {mustBeFinite, mustBePositive} = 1
    sampleArea_cm2 (1, 1) double {mustBeFinite, mustBePositive} = 1
end

wavelength = siliconExtracted.Wavelength_nm;
minimumWavelength = min(calibration.Wavelength_nm);
maximumWavelength = max(calibration.Wavelength_nm);
if any(wavelength < minimumWavelength | wavelength > maximumWavelength)
    error("IPCE:CalibrationRange", ...
        "所选波长超出标探校准范围 %.6g–%.6g nm；程序不会外推响应度。", ...
        minimumWavelength, maximumWavelength);
end

responsivity = interp1(calibration.Wavelength_nm, ...
    calibration.Responsivity_A_per_W, wavelength, "pchip");
if any(~isfinite(responsivity) | responsivity <= 0)
    error("IPCE:InvalidResponsivity", "插值得到的标探响应度包含无效值。");
end

siliconPhotocurrent = siliconExtracted.AbsPhotoCurrent_A;
siliconCollectedPower = siliconPhotocurrent ./ responsivity;
siliconCollectedPowerSE = siliconExtracted.PhotoCurrentSE_A ./ responsivity;
incidentPowerDensity = siliconCollectedPower / siliconArea_cm2;
incidentPowerDensitySE = siliconCollectedPowerSE / siliconArea_cm2;
if any(~isfinite(incidentPowerDensity) | incidentPowerDensity <= 0)
    error("IPCE:InvalidPowerDensity", ...
        "反算得到的单色光功率密度包含非正值或无效值。");
end

lightResult = table(wavelength, responsivity, ...
    siliconExtracted.MeanCurrent_A, siliconExtracted.PhotoCurrent_A, ...
    siliconPhotocurrent, siliconExtracted.PhotoCurrentSE_A, ...
    repmat(siliconArea_cm2, numel(wavelength), 1), ...
    incidentPowerDensity, incidentPowerDensitySE, ...
    siliconExtracted.SampleCount, ...
    'VariableNames', {'Wavelength_nm', 'SiResponsivity_A_per_W', ...
    'SiMeanCurrent_A', 'SiPhotoCurrentSigned_A', 'SiPhotocurrent_A', ...
    'SiPhotoCurrentSE_A', 'SiliconIlluminatedArea_cm2', ...
    'IncidentPowerDensity_W_cm2', 'IncidentPowerDensitySE_W_cm2', ...
    'SiSampleCount'});

ipceResult = table();
if isempty(sampleExtracted)
    return
end

sampleWavelength = sampleExtracted.Wavelength_nm;
if any(sampleWavelength < min(wavelength) | sampleWavelength > max(wavelength))
    error("IPCE:PowerInterpolationRange", ...
        ["样品波长 %.6g–%.6g nm 超出标探功率密度范围 %.6g–%.6g nm。" ...
        "程序不会对标探功率密度做范围外外推。"], ...
        min(sampleWavelength), max(sampleWavelength), ...
        min(wavelength), max(wavelength));
end

incidentPowerDensityAtSample = interp1(wavelength, incidentPowerDensity, ...
    sampleWavelength, "pchip");
incidentPowerDensitySEAtSample = interp1(wavelength, ...
    incidentPowerDensitySE, ...
    sampleWavelength, "linear");
if any(~isfinite(incidentPowerDensityAtSample) | ...
        incidentPowerDensityAtSample <= 0)
    error("IPCE:InvalidInterpolatedPowerDensity", ...
        "插值到样品波长的入射功率密度包含非正值或无效值。");
end

samplePhotocurrent = sampleExtracted.AbsPhotoCurrent_A;
samplePhotocurrentDensity = samplePhotocurrent / sampleArea_cm2;
samplePhotoCurrentDensitySE = ...
    sampleExtracted.PhotoCurrentSE_A / sampleArea_cm2;
constant_eV_nm = 1239.8419843320026;
ipcePercent = 100 * constant_eV_nm .* samplePhotocurrentDensity ./ ...
    (incidentPowerDensityAtSample .* sampleWavelength);

relativeSi = incidentPowerDensitySEAtSample ./ ...
    incidentPowerDensityAtSample;
relativeSample = samplePhotoCurrentDensitySE ./ samplePhotocurrentDensity;
ipceEstimatedSE = ipcePercent .* hypot(relativeSi, relativeSample);
ipceEstimatedSE(~isfinite(ipceEstimatedSE)) = NaN;
powerDensityInterpolated = ~ismembertol(sampleWavelength, wavelength, ...
    10 * eps(max(abs(wavelength))));

ipceResult = table(sampleWavelength, incidentPowerDensityAtSample, ...
    incidentPowerDensitySEAtSample, powerDensityInterpolated, ...
    sampleExtracted.MeanCurrent_A, sampleExtracted.PhotoCurrent_A, ...
    samplePhotocurrent, sampleExtracted.PhotoCurrentSE_A, ...
    repmat(sampleArea_cm2, numel(sampleWavelength), 1), ...
    samplePhotocurrentDensity, samplePhotoCurrentDensitySE, ...
    sampleExtracted.SampleCount, ipcePercent, ipceEstimatedSE, ...
    'VariableNames', {'Wavelength_nm', 'IncidentPowerDensity_W_cm2', ...
    'IncidentPowerDensitySE_W_cm2', 'PowerDensityInterpolated', ...
    'SampleMeanCurrent_A', ...
    'SamplePhotoCurrentSigned_A', 'SamplePhotocurrent_A', ...
    'SamplePhotoCurrentSE_A', 'SampleIlluminatedArea_cm2', ...
    'SamplePhotocurrentDensity_A_cm2', ...
    'SamplePhotoCurrentDensitySE_A_cm2', 'SampleSampleCount', ...
    'IPCE_percent', 'IPCE_EstimatedSE_percent'});
end
