function config = ipcePortablePackageConfig
%IPCEPORTABLEPACKAGECONFIG Return the verified portable-build manifest.

projectRoot = string(fileparts(mfilename("fullpath")));
defaults = ipceDefaultConfig();
defaultNames = [ ...
    defaults.CalibrationFile; ...
    defaults.SpectrumFile; ...
    defaults.SiliconTraceFile; ...
    defaults.SiliconAnchorFile];

config = struct( ...
    "ProjectRoot", projectRoot, ...
    "ReleaseName", "IPCEApp_R2023b_Windows_x64", ...
    "ArchiveName", "IPCEApp_R2023b_Windows_x64.zip", ...
    "ExecutableName", "IPCEApp.exe", ...
    "DefaultFiles", fullfile(projectRoot, defaultNames), ...
    "PortableReadme", fullfile(projectRoot, "PORTABLE_README_CN.txt"));
end
