function paths = ipceRepositoryPaths
%IPCEREPOSITORYPATHS Return stable source and shared-data locations.

matlabRoot = string(fileparts(mfilename("fullpath")));
repositoryRoot = string(fileparts(matlabRoot));
dataRoot = fullfile(repositoryRoot, "data");

paths = struct( ...
    "RepositoryRoot", repositoryRoot, ...
    "MatlabRoot", matlabRoot, ...
    "DataRoot", dataRoot, ...
    "DefaultsRoot", fullfile(dataRoot, "defaults"), ...
    "ExamplesRoot", fullfile(dataRoot, "examples"));
end
