function output = ipceLanguageCatalog(language, key, varargin)
%IPCELANGUAGECATALOG Return localized IPCEApp text with English fallback.

language = normalizeLanguage(language);
keys = [ ...
    "App.Title"; ...
    "Common.Import"; ...
    "Common.NotImported"; ...
    "Common.Cancel"; ...
    "Language.Label"; ...
    "Language.English"; ...
    "Language.Chinese"; ...
    "Status.Ready"; ...
    "Panel.Workflow"; ...
    "Tab.SiliconTrace"; ...
    "Tab.SampleTrace"; ...
    "Tab.Spectrum" ...
    ];
english = [ ...
    "IPCE Measurement and Analysis"; ...
    "Import"; ...
    "Not imported"; ...
    "Cancel"; ...
    "Language"; ...
    "English"; ...
    "中文"; ...
    "Ready"; ...
    "Measurement workflow"; ...
    "Silicon i-t"; ...
    "Sample i-t"; ...
    "Spectrum integration" ...
    ];
chinese = [ ...
    "IPCE 测量与分析"; ...
    "导入"; ...
    "尚未导入"; ...
    "取消"; ...
    "语言"; ...
    "English"; ...
    "中文"; ...
    "就绪"; ...
    "测量流程"; ...
    "标探 i-t"; ...
    "样品 i-t"; ...
    "光谱积分" ...
    ];

if language == "zh-CN"
    values = chinese;
else
    values = english;
end

if nargin < 2
    output = struct( ...
        "Language", language, ...
        "Keys", keys, ...
        "Values", values);
    return
end

key = string(key);
index = find(keys == key, 1);
if isempty(index)
    value = "[" + key + "]";
else
    value = values(index);
end
if ~isempty(varargin)
    value = string(sprintf(char(value), varargin{:}));
end
output = value;
end

function language = normalizeLanguage(language)
language = string(language);
if startsWith(lower(language), "zh")
    language = "zh-CN";
else
    language = "en-US";
end
end
