function [summary, curve] = ipceIntegrateSpectrum(ipceResult, spectrum, ...
    minimumWavelength, maximumWavelength)
%IPCEINTEGRATESPECTRUM Calculate spectrum-integrated current density.
%   spectrum irradiance must be in W m^-2 nm^-1 and IPCE in percent.
%   The returned current density assumes unity charge collection described
%   by the measured external IPCE:
%       J = q * integral(E_lambda * lambda/(h*c) * EQE d_lambda)

arguments
    ipceResult table
    spectrum table
    minimumWavelength (1, 1) double {mustBeFinite, mustBePositive}
    maximumWavelength (1, 1) double {mustBeFinite, mustBePositive}
end

if minimumWavelength >= maximumWavelength
    error("IPCE:InvalidIntegrationRange", ...
        "积分终止波长必须大于起始波长。");
end
if ~all(ismember(["Wavelength_nm", "IPCE_percent"], ...
        string(ipceResult.Properties.VariableNames)))
    error("IPCE:InvalidIPCEResult", ...
        "IPCE 结果必须包含 Wavelength_nm 和 IPCE_percent。");
end
if ~all(ismember(["Wavelength_nm", "Irradiance_W_m2_nm"], ...
        string(spectrum.Properties.VariableNames)))
    error("IPCE:InvalidSpectrum", ...
        "光谱必须包含波长和 W m^-2 nm^-1 辐照度。");
end

lowerCoverage = max(min(ipceResult.Wavelength_nm), ...
    min(spectrum.Wavelength_nm));
upperCoverage = min(max(ipceResult.Wavelength_nm), ...
    max(spectrum.Wavelength_nm));
if minimumWavelength < lowerCoverage || maximumWavelength > upperCoverage
    error("IPCE:IntegrationCoverage", ...
        ["积分范围 %.6g–%.6g nm 超出 IPCE 与光谱共同覆盖范围 " ...
        "%.6g–%.6g nm；程序不会外推。"], ...
        minimumWavelength, maximumWavelength, lowerCoverage, upperCoverage);
end

spectrumGrid = spectrum.Wavelength_nm( ...
    spectrum.Wavelength_nm > minimumWavelength & ...
    spectrum.Wavelength_nm < maximumWavelength);
wavelength = unique([minimumWavelength; spectrumGrid; maximumWavelength]);
irradiance = interp1(spectrum.Wavelength_nm, ...
    spectrum.Irradiance_W_m2_nm, wavelength, "linear");
ipcePercent = interp1(ipceResult.Wavelength_nm, ...
    ipceResult.IPCE_percent, wavelength, "pchip");

if any(~isfinite(irradiance)) || any(~isfinite(ipcePercent))
    error("IPCE:IntegrationInterpolation", ...
        "光谱或 IPCE 插值产生了无效值。");
end

planck = 6.62607015e-34;
speedOfLight = 299792458;
elementaryCharge = 1.602176634e-19;
wavelengthMetres = wavelength * 1e-9;
eqeFraction = ipcePercent / 100;
photonFlux = irradiance .* wavelengthMetres / (planck * speedOfLight);
spectralCurrent_A_m2_nm = elementaryCharge * photonFlux .* eqeFraction;
currentDensity_A_m2 = trapz(wavelength, spectralCurrent_A_m2_nm);
currentDensity_mA_cm2 = 0.1 * currentDensity_A_m2;
cumulativeCurrentDensity_mA_cm2 = ...
    0.1 * cumtrapz(wavelength, spectralCurrent_A_m2_nm);
spectralPower_W_m2 = trapz(wavelength, irradiance);

summary = table(minimumWavelength, maximumWavelength, ...
    currentDensity_mA_cm2, spectralPower_W_m2, numel(wavelength), ...
    "pchip(IPCE) + linear(spectrum)", ...
    'VariableNames', {'MinimumWavelength_nm', 'MaximumWavelength_nm', ...
    'IntegratedCurrentDensity_mA_cm2', 'IntegratedPower_W_m2', ...
    'IntegrationGridPoints', 'Interpolation'});

curve = table(wavelength, irradiance, ipcePercent, eqeFraction, ...
    photonFlux, 0.1 * spectralCurrent_A_m2_nm, ...
    cumulativeCurrentDensity_mA_cm2, ...
    'VariableNames', {'Wavelength_nm', 'Irradiance_W_m2_nm', ...
    'IPCE_percent', 'EQE_fraction', 'PhotonFlux_m2_s_nm', ...
    'SpectralCurrent_mA_cm2_nm', ...
    'CumulativeCurrentDensity_mA_cm2'});
end
