function text = ipceLocalizeException(language, identifier, sourceMessage)
%IPCELOCALIZEEXCEPTION Localize recoverable errors by stable identifier.

language = string(language);
if startsWith(lower(language), "zh")
    text = string(sourceMessage);
    return
end

identifier = string(identifier);
identifiers = [ ...
    "IPCE:FileNotFound"; "IPCE:AnchorFileNotFound"; ...
    "IPCE:ReferenceImportFailed"; "IPCE:AnchorImportFailed"; ...
    "IPCE:TraceImportFailed"; "IPCE:ExternalIPCEImportFailed"; ...
    "IPCE:SpectrumImportFailed"; "IPCE:SpectrumHeaderImportFailed"; ...
    "IPCE:InvalidReference"; "IPCE:InvalidAnchorFile"; ...
    "IPCE:InvalidTrace"; "IPCE:TraceUnitsRequired"; ...
    "IPCE:UnsupportedTimeUnit"; "IPCE:UnsupportedCurrentUnit"; ...
    "IPCE:UnsupportedExternalIPCE"; "IPCE:InvalidExternalIPCE"; ...
    "IPCE:SpectrumSheetNotFound"; "IPCE:SpectrumColumnMissing"; ...
    "IPCE:NoNumericSpectrumColumns"; "IPCE:InvalidSpectrum"; ...
    "IPCE:EmptyWavelengths"; "IPCE:MissingAnchors"; ...
    "IPCE:DuplicateAnchors"; "IPCE:NonMonotonicSchedule"; ...
    "IPCE:UnknownAlignmentMode"; "IPCE:InvalidSchedule"; ...
    "IPCE:InsufficientCoverage"; "IPCE:InvalidDarkRange"; ...
    "IPCE:DarkRangeOutsideTrace"; "IPCE:InsufficientDarkData"; ...
    "IPCE:EmptyWindow"; "IPCE:CalibrationRange"; ...
    "IPCE:InvalidResponsivity"; "IPCE:InvalidPowerDensity"; ...
    "IPCE:PowerInterpolationRange"; ...
    "IPCE:InvalidInterpolatedPowerDensity"; ...
    "IPCE:InvalidIntegrationRange"; "IPCE:InvalidIPCEResult"; ...
    "IPCE:IntegrationCoverage"; "IPCE:IntegrationInterpolation"; ...
    "IPCE:MissingCalculatedIPCE"; "IPCE:MissingExternalIPCE"; ...
    "IPCE:UnknownIPCESource"; "IPCE:DuplicateSpectrumColumns"; ...
    "IPCE:SpectrumReloadFailed"; "IPCE:MissingSpectrum"; ...
    "IPCE:NoExportSelection"; "IPCE:UnsupportedExport"; ...
    "IPCE:ExportVerificationFailed"; "IPCE:InvalidExportItems"; ...
    "IPCE:InvalidAxisLimits"; "IPCE:InvalidLogAxis"; ...
    "IPCE:UnknownAxisTarget"; "IPCE:InvalidAverageWindow"; ...
    "IPCE:MissingCalibration"; "IPCE:MissingSilicon"; ...
    "IPCE:MissingSample"; "IPCE:IncompleteAnchor"; ...
    "IPCE:InvalidAnchor" ...
    ];
messages = [ ...
    "The selected file was not found or cannot be accessed."; ...
    "The selected anchor file was not found or cannot be accessed."; ...
    "The detector-calibration file could not be imported."; ...
    "The wavelength-time anchor file could not be imported."; ...
    "The i-t file could not be imported."; ...
    "The external IPCE file could not be imported."; ...
    "The spectrum worksheet could not be imported."; ...
    "The spectrum headers could not be read."; ...
    "The detector calibration is invalid or contains too few usable points."; ...
    "The anchor data are invalid, incomplete, duplicated, or out of range."; ...
    "The i-t data are invalid or contain too few usable points."; ...
    "Time or current units could not be identified. Select them explicitly."; ...
    "The selected time unit is unsupported."; ...
    "The selected current unit is unsupported."; ...
    "External IPCE supports TXT, CSV, XLS, and XLSX files only."; ...
    "The external IPCE data are invalid or contain too few usable points."; ...
    "The requested spectrum worksheet was not found."; ...
    "The selected spectrum column does not exist."; ...
    "The worksheet does not contain enough numeric spectrum columns."; ...
    "The spectrum data are invalid or contain too few usable points."; ...
    "The wavelength sequence cannot be empty."; ...
    "Anchor alignment requires at least one valid wavelength-time pair."; ...
    "Anchor wavelengths must be unique."; ...
    "Anchor-derived times must increase along the scan direction."; ...
    "The selected time-alignment mode is unsupported."; ...
    "The generated wavelength schedule is invalid."; ...
    "The i-t data do not cover the required measurement schedule."; ...
    "The dark-current interval is invalid."; ...
    "The dark-current interval is outside the i-t data range."; ...
    "The dark-current interval contains too few data points."; ...
    "A wavelength averaging window contains no usable data."; ...
    "Selected wavelengths exceed the detector-calibration range; responsivity is not extrapolated."; ...
    "Interpolated detector responsivity contains invalid values."; ...
    "Calculated incident power density contains non-positive or invalid values."; ...
    "Sample wavelengths exceed the calculated detector power-density range."; ...
    "Interpolated incident power density contains non-positive or invalid values."; ...
    "The integration end wavelength must exceed the start wavelength."; ...
    "The IPCE result table does not contain the required columns."; ...
    "The requested range exceeds the common IPCE/spectrum wavelength coverage; extrapolation is disabled."; ...
    "Spectrum or IPCE interpolation produced invalid values."; ...
    "Calculated IPCE is selected. Calculate sample IPCE first."; ...
    "Imported external IPCE is selected. Import an external IPCE file first."; ...
    "The selected IPCE source is unsupported."; ...
    "Wavelength and integration columns must be different."; ...
    "The spectrum could not be reloaded with the selected worksheet or columns."; ...
    "Import reference spectrum data first."; ...
    "Select at least one output item."; ...
    "The selected export format is unsupported."; ...
    "The exported file could not be verified on disk."; ...
    "The export bundle is invalid."; ...
    "An axis maximum must exceed its minimum."; ...
    "Logarithmic axis limits must be positive."; ...
    "The selected plot target is unsupported."; ...
    "In fixed-delay mode, averaging duration cannot exceed delay."; ...
    "Import silicon-detector responsivity calibration first."; ...
    "Import silicon-detector i-t data first."; ...
    "Import sample i-t data first."; ...
    "An anchor row is incomplete; wavelength and time are both required."; ...
    "Anchor wavelengths must be greater than zero." ...
    ];

if numel(identifiers) ~= numel(messages)
    error("IPCE:LocalizationCatalogMismatch", ...
        "Exception identifiers and localized messages must have equal length.");
end

match = find(identifiers == identifier, 1);
if isempty(match)
    text = "[Unlocalized error: " + identifier + "]";
else
    text = messages(match);
end
end
