function output = ipceLocalizeLiteral(language, input)
%IPCELOCALIZELITERAL Translate MATLAB UI literals without changing data.
%   Chinese source strings are kept as the localization source of truth.
%   Non-text values pass through unchanged so this helper can be used for
%   component Text, Title, Tooltip, Items, and ColumnName properties.

language = normalizeLanguage(language);
if language == "zh-CN" || ~(ischar(input) || isstring(input) || iscell(input))
    output = input;
    return
end

if iscell(input)
    output = input;
    for index = 1:numel(input)
        output{index} = ipceLocalizeLiteral(language, input{index});
    end
    return
end

wasCharacterVector = ischar(input);
values = string(input);
for index = 1:numel(values)
    values(index) = translateScalar(values(index));
end
if wasCharacterVector
    output = char(values);
else
    output = values;
end
end

function value = translateScalar(value)
[source, english] = exactTranslations();
match = find(source == value, 1);
if ~isempty(match)
    value = english(match);
    return
end

% Longest and most specific phrases come first. This also provides a safe
% English rendering for dynamic messages assembled with sprintf.
replacements = [ ...
    "硅基标探", "silicon reference detector"; ...
    "硅标探", "silicon reference detector"; ...
    "单色光功率密度", "monochromatic incident power density"; ...
    "累计积分电流密度", "cumulative integrated current density"; ...
    "光谱辐照度", "spectral irradiance"; ...
    "暗电流区间", "dark-current interval"; ...
    "暗区间", "dark-current interval"; ...
    "时间对齐方式", "time-alignment mode"; ...
    "确认点后平均", "averaging after confirmation"; ...
    "扫描与取点参数", "scan and sampling parameters"; ...
    "标探响应度", "detector responsivity"; ...
    "外部导入", "external import"; ...
    "本软件计算", "calculated by this application"; ...
    "工作表", "worksheet"; ...
    "固定模式", "fixed-delay mode"; ...
    "锚点插值", "anchor interpolation"; ...
    "锚点", "anchor"; ...
    "标探", "detector"; ...
    "样品", "sample"; ...
    "波长", "wavelength"; ...
    "时间", "time"; ...
    "电流", "current"; ...
    "功率密度", "power density"; ...
    "积分", "integration"; ...
    "光谱", "spectrum"; ...
    "结果", "results"; ...
    "导入", "import"; ...
    "导出", "export"; ...
    "计算", "calculate"; ...
    "设置", "settings"; ...
    "选择", "select"; ...
    "起始", "start"; ...
    "终止", "end"; ...
    "起点", "start"; ...
    "终点", "end"; ...
    "范围", "range"; ...
    "列", "column"; ...
    "行", "row"; ...
    "文件", "file"; ...
    "数据", "data"; ...
    "图形", "plot"; ...
    "图上", "on plot"; ...
    "确认", "confirm"; ...
    "添加", "add"; ...
    "删除", "delete"; ...
    "读取", "read"; ...
    "尚未", "not yet "; ...
    "已", ""; ...
    "错误", "error"; ...
    "成功", "successful"; ...
    "失败", "failed"; ...
    "推荐", "recommended"; ...
    "平均", "average"; ...
    "面积", "area"; ...
    "最小值", "minimum"; ...
    "最大值", "maximum"; ...
    "线性", "linear"; ...
    "对数", "logarithmic"; ...
    "取消", "cancel" ...
    ];
for index = 1:size(replacements, 1)
    value = replace(value, replacements(index, 1), replacements(index, 2));
end
value = replace(value, ["（", "）", "：", "；", "，", "。", "、"], ...
    [" (", ")", ": ", "; ", ", ", ".", ", "]);

% No Chinese fragment is allowed to leak into English mode. Exact mappings
% below cover the authored UI; this final guard handles unforeseen dynamic
% exception text while leaving numbers, units, and filenames intact.
value = regexprep(value, '[\x{4e00}-\x{9fff}]', ' ');
value = regexprep(value, '\s+', ' ');
value = strtrim(value);
end

function [source, english] = exactTranslations()
source = [ ...
    "IPCE 测量与分析"; "测量流程"; ...
    "硅基标探 → 单色光功率密度 → 样品 IPCE"; ...
    "标探响应度 (.xlsx)"; "硅标探 i-t（0 V）"; "样品 i-t"; ...
    "导入"; "尚未导入"; "扫描与取点参数"; ...
    "编辑标探参数"; "编辑样品参数"; ...
    "起始波长 (nm)"; "终止波长 (nm)"; "步长 (nm)"; ...
    "时间对齐方式"; "锚点插值（推荐）"; "固定 Delay"; ...
    "固定模式：标探首时刻"; "固定模式：样品首时刻"; ...
    "图上选"; "驻留 / Delay (s)"; "确认点后平均 (s)"; ...
    "扣除指定区间暗电流"; "设置暗区间"; ...
    "标探面积 (cm²)"; "样品面积 (cm²)"; ...
    "标探调度"; "样品调度"; "功率密度与 IPCE"; ...
    "时间对齐"; "标探 i-t"; "光谱积分"; "结果表"; ...
    "标探锚点"; "样品锚点"; "添加行"; "删除行"; ...
    "新增图上选点"; "首个对齐参考"; ...
    "由锚点生成的波长–时间调度"; ...
    "由硅标探反算的单色光功率密度"; "样品 IPCE"; ...
    "① 反算单色光功率密度"; "② 计算样品 IPCE"; ...
    "导入 IPCE"; "尚未导入外部 IPCE"; ...
    "IPCE 数据源"; "本软件计算结果"; "外部导入 IPCE"; ...
    "导入光谱"; "工作表"; "波长列"; "积分列"; ...
    "尚未读取表头"; "积分起点"; "积分终点"; "计算积分 J"; ...
    "光谱与样品 IPCE"; "累计积分电流密度随波长变化"; ...
    "波长 (nm)"; "确认时间 (s)"; "时间 (s)"; "电流 (A)"; ...
    "入射功率密度 (\muW cm^{-2})"; ...
    "光谱辐照度 (W m^{-2} nm^{-1})"; ...
    "累计积分电流密度 (mA cm^{-2})"; ...
    "请导入标准光谱"; "请导入样品 i-t 后计算 IPCE"; ...
    "计算积分后显示累计电流密度"; ...
    "调度预览：请补全或检查锚点"; ...
    "图形设置"; "应用范围与刻度"; "自动范围"; ...
    "线性"; "对数"; "X 轴"; "Y 轴"; ...
    "最小值"; "最大值"; "刻度类型"; ...
    "导出结果（XLSX / CSV / MAT）"; "选择导出内容"; ...
    "选择文件格式和输出参数"; "选择路径并导出"; ...
    "Excel 工作簿"; "取消"; "确认并加入"; ...
    "就绪"; "English"; "中文"; ...
    "导出成功：%s"; "无法完成计算"; ...
    "已读取标探响应度：%d 点，%.6g–%.6g nm。"; ...
    "请先导入标准光谱数据。"; ...
    "光谱积分完成（%s）：%.6g–%.6g nm，J = %.6g mA cm^{-2}。"; ...
    "导出成功"; "导出失败"; "文件已写入："; ...
    "没有可导出的结果"; ...
    "请先计算功率密度/IPCE，或导入外部 IPCE。" ...
    ];
english = [ ...
    "IPCE Measurement and Analysis"; "Measurement workflow"; ...
    "Silicon reference detector → monochromatic power density → sample IPCE"; ...
    "Detector responsivity (.xlsx)"; "Silicon detector i-t (0 V)"; "Sample i-t"; ...
    "Import"; "Not imported"; "Scan and sampling parameters"; ...
    "Edit detector parameters"; "Edit sample parameters"; ...
    "Start wavelength (nm)"; "End wavelength (nm)"; "Step (nm)"; ...
    "Time-alignment mode"; "Anchor interpolation (recommended)"; "Fixed delay"; ...
    "Fixed mode: detector first time"; "Fixed mode: sample first time"; ...
    "Pick on plot"; "Dwell / delay (s)"; "Average after confirmation (s)"; ...
    "Subtract dark current over specified intervals"; "Set dark intervals"; ...
    "Detector area (cm²)"; "Sample area (cm²)"; ...
    "Detector schedule"; "Sample schedule"; "Power density and IPCE"; ...
    "Time alignment"; "Detector i-t"; "Spectrum integration"; "Results table"; ...
    "Detector anchors"; "Sample anchors"; "Add row"; "Delete row"; ...
    "Add point from plot"; "First alignment reference"; ...
    "Wavelength-time schedule generated from anchors"; ...
    "Monochromatic power density calculated from silicon detector"; "Sample IPCE"; ...
    "① Calculate monochromatic power density"; "② Calculate sample IPCE"; ...
    "Import IPCE"; "External IPCE not imported"; ...
    "IPCE source"; "Calculated results"; "Imported external IPCE"; ...
    "Import spectrum"; "Worksheet"; "Wavelength column"; "Integration column"; ...
    "Headers not read"; "Integration start"; "Integration end"; "Calculate integrated J"; ...
    "Spectrum and sample IPCE"; "Cumulative integrated current density vs wavelength"; ...
    "Wavelength (nm)"; "Confirmation time (s)"; "Time (s)"; "Current (A)"; ...
    "Incident power density (\muW cm^{-2})"; ...
    "Spectral irradiance (W m^{-2} nm^{-1})"; ...
    "Cumulative integrated current density (mA cm^{-2})"; ...
    "Import a reference spectrum"; "Import sample i-t data and calculate IPCE"; ...
    "Calculate the integral to display cumulative current density"; ...
    "Schedule preview: complete or check the anchors"; ...
    "Plot settings"; "Apply range and scale"; "Auto range"; ...
    "Linear"; "Logarithmic"; "X axis"; "Y axis"; ...
    "Minimum"; "Maximum"; "Scale type"; ...
    "Export results (XLSX / CSV / MAT)"; "Select export content"; ...
    "Select file format and output options"; "Choose path and export"; ...
    "Excel workbook"; "Cancel"; "Confirm and add"; ...
    "Ready"; "English"; "中文"; ...
    "Export successful: %s"; "Unable to complete calculation"; ...
    "Detector responsivity loaded: %d points, %.6g–%.6g nm."; ...
    "Import reference spectrum data first."; ...
    "Spectrum integration complete (%s): %.6g–%.6g nm, J = %.6g mA cm^{-2}."; ...
    "Export successful"; "Export failed"; "Files written:"; ...
    "No results available for export"; ...
    "Calculate power density/IPCE or import external IPCE first." ...
    ];

additional = [ ...
    "语言 / Language", "Language"; ...
    "固定模式的驻留时间；锚点模式只有一个锚点时作为时间步长。", "Dwell time in fixed-delay mode; with one anchor, it is used as the time step."; ...
    "标探和样品分别使用用户输入或图上选择的暗电流时间区间。", "The detector and sample use independently entered or plot-selected dark-current intervals."; ...
    "硅标探实际受光面积。", "Actual illuminated area of the silicon detector."; ...
    "样品有效受光面积；假设光斑辐照度均匀。", "Effective illuminated sample area, assuming uniform spot irradiance."; ...
    "锚点只表示此时已经输出目标波长；程序从确认点向后取稳态均值。", "An anchor confirms that the target wavelength is already present; steady-state averaging starts after that point."; ...
    "提示：在“时间对齐”页输入波长–时间锚点，或选择锚点行后到图上确认。", "Tip: enter wavelength-time anchors on the Time Alignment tab, or select an anchor row and confirm it on the plot."; ...
    "若光电流方向为负，程序保留有符号列，但用 |ΔI| 计算功率密度和 IPCE。", "For negative photocurrent, signed columns are retained while |ΔI| is used for power density and IPCE."; ...
    "界面不对标探响应度做范围外外推。", "Detector responsivity is not extrapolated beyond its range."; ...
    "锚点时间只保证单色仪此时已经输出该波长，不假定它是切换起点。", "An anchor only confirms that the monochromator has reached the wavelength; it is not assumed to be the switching instant."; ...
    "可直接编辑；也可先放大 i-t 图，再新增图上选点。", "Edit directly, or zoom the i-t plot and add a point from the plot."; ...
    "两点以上分段线性插值，两端按最近两点斜率外推。", "Piecewise linear interpolation is used for two or more points; endpoints use the nearest-pair slope."; ...
    "暗电流不会再默认取扫描前一段。请为标探和样品分别输入明确时间区间，", "Dark current is not inferred from a pre-scan segment. Enter explicit intervals for detector and sample,"; ...
    "或先在对应 i-t 图上放大，再依次点击暗区间起点和终点。计算时取该区间的平均电流。", "or zoom the corresponding i-t plot and select the interval start and end. The interval mean is used."; ...
    "每张图都可直接使用右上角工具栏放大、缩小、平移和恢复。", "Use the toolbar at the upper right of each plot to zoom, pan, and restore the view."; ...
    "这里还可以精确输入 X/Y 显示范围，并分别选择线性或对数刻度。", "Enter exact X/Y display limits here and choose linear or logarithmic scales independently."; ...
    "暗电流", "Dark current"; "暗电流区间", "Dark-current interval"; ...
    "暗区间起点 (s)", "Dark interval start (s)"; "暗区间终点 (s)", "Dark interval end (s)"; ...
    "图上操作", "Plot selection"; "依次选择起点、终点", "Select start, then end"; ...
    "目标图形", "Target plot"; "读取当前范围", "Read current range"; ...
    "光谱积分（左轴）", "Spectrum integration (left axis)"; ...
    "光谱积分（右轴）", "Spectrum integration (right axis)"; ...
    "累计积分电流密度", "Cumulative integrated current density"; ...
    "光谱数据与积分范围", "Spectrum data and integration range"; ...
    "积分范围", "Integration range"; "累计积分 J", "Cumulative integrated J"; ...
    "最终积分 J", "Final integrated J"; "原始 i-t", "Raw i-t"; ...
    "窗口均值", "Window mean"; "首个对齐参考", "First alignment reference"; ...
    "确认已有行", "Confirm selected row"; "导入 TXT", "Import TXT"; ...
    "标探校准表 (*.xlsx, *.xls, *.csv)", "Detector calibration (*.xlsx, *.xls, *.csv)"; ...
    "所有文件", "All files"; "i-t 数据", "i-t data"; ...
    "两列 IPCE 数据 (*.txt, *.csv, *.xlsx, *.xls)", "Two-column IPCE data (*.txt, *.csv, *.xlsx, *.xls)"; ...
    "光谱数据 (*.xls, *.xlsx, *.csv)", "Spectrum data (*.xls, *.xlsx, *.csv)"; ...
    "两列锚点数据 (*.txt, *.csv, *.xlsx, *.xls)", "Two-column anchor data (*.txt, *.csv, *.xlsx, *.xls)"; ...
    "选择硅标探响应度校准表", "Select silicon-detector responsivity calibration"; ...
    "选择硅标探 i-t 文件", "Select silicon-detector i-t file"; ...
    "选择样品 i-t 文件", "Select sample i-t file"; ...
    "选择外部 IPCE 文件（第 1 列 nm，第 2 列 %）", "Select external IPCE file (column 1: nm; column 2: %)"; ...
    "选择标准光谱文件", "Select reference spectrum file"; ...
    "选择%s波长–时间锚点文件", "Select %s wavelength-time anchor file"; ...
    "请选择原始时间列单位。", "Select the source time-column unit."; ...
    "请选择原始电流列单位。导入后将统一换算为 A。", "Select the source current-column unit. Values will be converted to A."; ...
    "选择时间单位", "Select time unit"; "选择电流单位", "Select current unit"; ...
    "选择导出内容", "Select export content"; "文件格式", "File format"; ...
    "标探功率密度结果", "Detector power-density results"; ...
    "样品 IPCE 结果", "Sample IPCE results"; ...
    "光谱积分汇总与积分曲线", "Spectrum-integration summary and cumulative curve"; ...
    "参数、源文件和可用锚点", "Parameters, source files, and available anchors"; ...
    "标探/样品窗口提取统计", "Detector/sample window-extraction statistics"; ...
    "保留详细误差、符号电流和采样数列", "Keep detailed errors, signed currents, and sample counts"; ...
    "CSV 选择多项时会输出多个带后缀的文件。导出成功后会显示绝对路径。", "Selecting multiple CSV outputs creates suffixed files. Absolute paths are shown after export."; ...
    "选择导出路径", "Select export path"; ...
    "至少选择一项输出内容。", "Select at least one output item."; ...
    "不支持的导出格式：%s", "Unsupported export format: %s"; ...
    "错误：%s", "Error: %s"; ...
    "请先导入硅标探 i-t。", "Import silicon-detector i-t data first."; ...
    "请先导入样品 i-t。", "Import sample i-t data first."; ...
    "无法确认锚点", "Unable to confirm anchor"; "无法新增锚点", "Unable to add anchor"; ...
    "无法选点", "Unable to select point"; "无法选择暗区间", "Unable to select dark-current interval"; ...
    "请先选择一个锚点行，并在第一列填写波长。", "Select an anchor row and enter its wavelength in the first column."; ...
    "锚点波长缺失", "Anchor wavelength missing"; ...
    "请先用图上工具栏或滚轮放大，再单击目标点；随后可确认/修改时间并输入波长。", "Zoom with the plot toolbar or mouse wheel, then click the target point. Confirm or edit the time and enter a wavelength."; ...
    "请在“标探 i-t”图上单击第一个波长驻留窗口的起始位置。", "Click the start of the first wavelength dwell window on the Detector i-t plot."; ...
    "请在“样品 i-t”图上单击第一个波长驻留窗口的起始位置。", "Click the start of the first wavelength dwell window on the Sample i-t plot."; ...
    "已添加锚点行；请填写波长和时间，或填写波长后在图上确认时间。", "Anchor row added. Enter wavelength and time, or enter wavelength and confirm the time on the plot."; ...
    "光谱积分将使用外部导入 IPCE。", "Spectrum integration will use imported external IPCE."; ...
    "光谱积分将使用本软件计算的样品 IPCE。", "Spectrum integration will use the sample IPCE calculated by this application."; ...
    "已应用图形显示范围和刻度类型。", "Plot limits and scale types applied."; ...
    "已按当前数据自动选择显示范围。", "Display limits selected automatically from current data."; ...
    "暗区间起点和终点不能相同，请重新选择。", "Dark-interval start and end cannot be equal. Select again."; ...
    "请先导入标探响应度和硅标探 i-t。", "Import detector responsivity and silicon-detector i-t data first."; ...
    "功率密度计算完成：%d 个波长，调度 %.3f–%.3f s，功率密度 %.4g–%.4g μW cm^{-2}。", "Power-density calculation complete: %d wavelengths, schedule %.3f–%.3f s, power density %.4g–%.4g μW cm^{-2}."; ...
    "IPCE 计算完成：%d 个波长。中位数 %.4g%%，最大值 %.4g%%。", "IPCE calculation complete: %d wavelengths; median %.4g%%, maximum %.4g%%."; ...
    "已读取外部 IPCE：%d 点，%.6g–%.6g nm；数据源已切换为外部导入。", "External IPCE loaded: %d points, %.6g–%.6g nm; source switched to external import."; ...
    "已读取光谱：%d 点，%.6g–%.6g nm；波长列“%s”，积分列“%s”。", "Spectrum loaded: %d points, %.6g–%.6g nm; wavelength column '%s', integration column '%s'."; ...
    "光谱与 %s（积分前进行波长插值）", "Spectrum and %s (wavelength interpolation before integration)"; ...
    "当前选择了“本软件计算结果”，请先计算样品 IPCE。", "Calculated results are selected. Calculate sample IPCE first."; ...
    "当前选择了“外部导入 IPCE”，请先导入外部 IPCE 文件。", "Imported external IPCE is selected. Import an external IPCE file first."; ...
    "无法识别 IPCE 数据源：%s。", "Unrecognized IPCE source: %s."; ...
    "波长序列不能为空。", "The wavelength sequence cannot be empty."; ...
    "锚点模式至少需要一组有效的“波长–时间”数据。", "Anchor mode requires at least one valid wavelength-time pair."; ...
    "锚点波长不能重复。", "Anchor wavelengths must be unique."; ...
    "锚点生成的时间不是沿扫描方向严格递增。", "Anchor-derived times are not strictly increasing along the scan direction."; ...
    "请检查波长顺序和锚点时间。", "Check wavelength order and anchor times."; ...
    "生成的波长驻留窗口包含非正时长。", "The generated wavelength dwell schedule contains a non-positive duration."; ...
    "未知的时间对齐模式：%s", "Unknown time-alignment mode: %s"; ...
    "所选波长超出标探校准范围 %.6g–%.6g nm；程序不会外推响应度。", "Selected wavelengths exceed the detector-calibration range %.6g–%.6g nm; responsivity will not be extrapolated."; ...
    "样品波长 %.6g–%.6g nm 超出标探功率密度范围 %.6g–%.6g nm。", "Sample wavelengths %.6g–%.6g nm exceed the detector power-density range %.6g–%.6g nm."; ...
    "暗电流区间终点必须晚于起点。请在界面输入或图上选择有效区间。", "The dark-current interval must end after it starts. Enter or select a valid interval."; ...
    "调度需要 %.3f–%.3f s，但数据仅覆盖 %.3f–%.3f s。", "The schedule requires %.3f–%.3f s, but the data cover only %.3f–%.3f s."; ...
    "积分终止波长必须大于起始波长。", "The integration end wavelength must exceed the start wavelength."; ...
    "光谱或 IPCE 插值产生了无效值。", "Spectrum or IPCE interpolation produced invalid values."; ...
    "外部 IPCE 仅支持 TXT、CSV、XLS 和 XLSX 文件。", "External IPCE supports TXT, CSV, XLS, and XLSX files only."; ...
    "外部 IPCE 文件中的有效波长/IPCE 数据少于两个点。", "The external IPCE file contains fewer than two valid wavelength/IPCE points."; ...
    "未能识别出 i-t 文件的时间列和电流列。", "Could not identify the time and current columns in the i-t file."; ...
    "无法从 i-t 表头识别时间或电流单位。时间列“%s”，电流列“%s”。请在导入时明确选择单位。", "Could not identify time or current units from the i-t headers. Time column '%s', current column '%s'. Select the units during import."; ...
    "找不到 i-t 文件：%s", "i-t file not found: %s"; ...
    "找不到标探校准文件：%s", "Detector calibration file not found: %s"; ...
    "找不到光谱文件：%s", "Spectrum file not found: %s"; ...
    "波长列和积分列不能选择同一列。", "Wavelength and integration columns must be different."; ...
    "固定 Delay 模式下，取样时长不能大于对应的 Delay。", "In fixed-delay mode, the averaging duration cannot exceed the corresponding delay."; ...
    "坐标轴最大值必须大于最小值。", "An axis maximum must exceed its minimum."; ...
    "X 轴使用对数刻度时，显示范围必须全部大于 0。", "X-axis limits must be positive when using a logarithmic scale."; ...
    "Y 轴使用对数刻度时，显示范围必须全部大于 0。", "Y-axis limits must be positive when using a logarithmic scale." ...
    ];
source = [source; additional(:, 1)];
english = [english; additional(:, 2)];
end

function language = normalizeLanguage(language)
if startsWith(lower(string(language)), "zh")
    language = "zh-CN";
else
    language = "en-US";
end
end
