<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPCE.Core\IPCE.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MatFileHandler" />
    <PackageReference Include="NPOI" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\data\defaults\标准硅探测器校准结果_证书编号 GXgf2026-01645.xlsx">
      <LogicalName>IPCE.IO.Defaults.标准硅探测器校准结果_证书编号 GXgf2026-01645.xlsx</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\data\defaults\标准太阳能光谱数据.xls">
      <LogicalName>IPCE.IO.Defaults.标准太阳能光谱数据.xls</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\data\defaults\Si-i t [300 1100] nm-grating 2-filter.txt">
      <LogicalName>IPCE.IO.Defaults.Si-i t [300 1100] nm-grating 2-filter.txt</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\data\defaults\Si-i t [300 1100] nm-grating 2-filter-time match.txt">
      <LogicalName>IPCE.IO.Defaults.Si-i t [300 1100] nm-grating 2-filter-time match.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
